# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-03-17 16:50:26
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def artesian():  # artesian_calc

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    Sc2HeadPts_Y20 = "Sc2HeadPts_Y20"
    topo_aboveSL_tif = arcpy.Raster("topo_aboveSL.tif")

    # Process: Select Layer By Attribute (Select Layer By Attribute) (management)
    Clean_version, Count = arcpy.management.SelectLayerByAttribute(in_layer_or_view=Sc2HeadPts_Y20, where_clause="Field4 <> 1.00000002E+30")

    # Process: Natural Neighbor (Natural Neighbor) (sa)
    sc2heady20_tif = "C:\\Users\\mjasper\\Documents\\_Projects\\Renascor\\Rasters_ArtesianScratch\\sc2heady20.tif"
    Natural_Neighbor = sc2heady20_tif
    sc2heady20_tif = arcpy.sa.NaturalNeighbor(Clean_version, "Field4", "86.09")
    sc2heady20_tif.save(Natural_Neighbor)


    # Process: Raster Calculator (Raster Calculator) (sa)
    sc2heady20_minustopo_tif = "C:\\Users\\mjasper\\Documents\\_Projects\\Renascor\\Rasters_ArtesianScratch\\sc2heady20_minustopo.tif"
    Raster_Calculator = sc2heady20_minustopo_tif
    sc2heady20_minustopo_tif = sc2heady20_tif - topo_aboveSL_tif
    sc2heady20_minustopo_tif.save(Raster_Calculator)


    # Process: Extract by Attributes (Extract by Attributes) (sa)
    sc2heady20_artes_tif = "C:\\Users\\mjasper\\Documents\\_Projects\\Renascor\\Rasters_ArtesianScratch\\sc2heady20_artes.tif"
    Extract_by_Attributes = sc2heady20_artes_tif
    sc2heady20_artes_tif = arcpy.sa.ExtractByAttributes(sc2heady20_minustopo_tif, "VALUE >= 0")
    sc2heady20_artes_tif.save(Extract_by_Attributes)


    # Process: Int (Int) (sa)
    sc2heady20_artes_int_tif = "C:\\Users\\mjasper\\Documents\\_Projects\\Renascor\\Rasters_ArtesianScratch\\sc2heady20_artes_int.tif"
    Int = sc2heady20_artes_int_tif
    sc2heady20_artes_int_tif = arcpy.sa.Int(sc2heady20_artes_tif)
    sc2heady20_artes_int_tif.save(Int)


    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    sc2heady20_artes_poly = "C:\\Users\\mjasper\\Documents\\_Projects\\Renascor\\Renascor_Layers.gdb\\sc2heady20_artes_poly"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=sc2heady20_artes_int_tif, out_polygon_features=sc2heady20_artes_poly)

    # Process: Dissolve (Dissolve) (management)
    sc2heady20_artes_poly_dissolv = "C:\\Users\\mjasper\\Documents\\_Projects\\Renascor\\Renascor_Layers.gdb\\sc2heady20_artes_poly_dissolv"
    arcpy.management.Dissolve(in_features=sc2heady20_artes_poly, out_feature_class=sc2heady20_artes_poly_dissolv, multi_part="SINGLE_PART", unsplit_lines="UNSPLIT_LINES")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\mjasper\\Documents\\_Projects\\Yakama\\GroundwaterDatabase11_21\\GroundwaterDatabase11_21.gdb", workspace="C:\\Users\\mjasper\\Documents\\_Projects\\Yakama\\GroundwaterDatabase11_21\\GroundwaterDatabase11_21.gdb"):
        artesian()
